apiVersion: v1
kind: Service
metadata:
  name: my-hello-app
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: my-hello-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-hello-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-hello-app
    spec:
      containers:
      - name: my-hello-app
        image: jgerth/my-hello-app
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-curl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-curl
    spec:
      containers:
      - name: nginx-curl
        image: rstarmer/nginx-curl
        ports:
        - containerPort: 80
